<a href="https://colab.research.google.com/github/rodrigoiyg27/TopicosEspeciales2026/blob/main/Clase5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url_ventas = "https://raw.githubusercontent.com/rodrigoiyg27/TopicosEspeciales2026/main/ventas.csv"
url_clientes = "https://raw.githubusercontent.com/rodrigoiyg27/TopicosEspeciales2026/main/clientes.csv"

ventas = pd.read_csv(url_ventas)
clientes = pd.read_csv(url_clientes)

print("Ventas cargado:", ventas.shape)
print("Clientes cargado:", clientes.shape)

Ventas cargado: (18, 8)
Clientes cargado: (8, 3)

Exploración inicial

In [ ]:
# .head() muestra las primeras filas para confirmar que la carga fue correcta
print("Primeras filas de ventas")
display(ventas.head())

print("\nPrimeras filas de clientes ")
display(clientes.head())

# .info() muestra tipos de dato por columna y cuántos valores no nulos tiene cada una
print("\n Info de ventas ")
ventas.info()

print("\nInfo de clientes")
clientes.info()

Primeras filas de ventas

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Categoria
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,Decoracion
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,Decoracion
2,536366,22633,HAND WARMER UNION JACK,6,1.85,17850,United Kingdom,Regalos
3,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,13047,United Kingdom,Regalos
4,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,3.75,13047,United Kingdom,Regalos

Primeras filas de clientes

   CustomerID         Country   Segmento
0       17850  United Kingdom  Minorista
1       13047  United Kingdom  Minorista
2       12583          France  Mayorista
3       13748  United Kingdom  Minorista
4       15100  United Kingdom  Mayorista

 Info de ventas
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    18 non-null     object
 1   StockCode    18 non-null     object
 2   Description  18 non-null     object
 3   Quantity     18 non-null     int64
 4   UnitPrice    18 non-null     float64
 5   CustomerID   18 non-null     int64
 6   Country      18 non-null     object
 7   Categoria    18 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.3+ KB

Info de clientes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  8 non-null      int64
 1   Country     8 non-null      object
 2   Segmento    8 non-null      object
dtypes: int64(1), object(2)
memory usage: 324.0+ bytes

Estadistica descriptivas generales

In [ ]:
# .describe() resume las columnas numéricas: promedio, mínimo, máximo, cuartiles
print("=== Estadísticas descriptivas de ventas ===")
display(ventas.describe())

# include='object' hace lo mismo pero para columnas de texto/categóricas:
# muestra cuántos valores únicos hay y cuál es el más frecuente
print("\n=== Estadísticas descriptivas de columnas categóricas ===")
display(ventas.describe(include='object'))

=== Estadísticas descriptivas de ventas ===

        Quantity  UnitPrice    CustomerID
count  18.000000  18.000000     18.000000
mean   20.222222   3.393889  14862.722222
std    24.329976   2.141970   2128.587264
min   -24.000000   1.060000  12583.000000
25%     6.000000   2.100000  13047.000000
50%    11.000000   3.170000  14688.000000
75%    30.000000   3.750000  17210.250000
max    80.000000  10.950000  17850.000000

=== Estadísticas descriptivas de columnas categóricas ===

,InvoiceNo,StockCode,Description,Country,Categoria
count,18,18,18,18,18
unique,11,17,17,2,2
top,536370,22728,ALARM CLOCK BAKELIKE PINK,United Kingdom,Regalos
freq,3,2,2,14,10

Comprobación de valores nulos

In [ ]:

print("Valores nulos en ventas ")
print(ventas.isnull().sum())

print("\n Valores nulos en clientes ")
print(clientes.isnull().sum())

#porcentaje de nulos por columna (útil cuando el dataset es más grande)
print("\n % de nulos por columna en ventas ")
print((ventas.isnull().mean() * 100).round(2))

Valores nulos en ventas
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
UnitPrice      0
CustomerID     0
Country        0
Categoria      0
dtype: int64

 Valores nulos en clientes
CustomerID    0
Country       0
Segmento      0
dtype: int64

 % de nulos por columna en ventas
InvoiceNo      0.0
StockCode      0.0
Description    0.0
Quantity       0.0
UnitPrice      0.0
CustomerID     0.0
Country        0.0
Categoria      0.0
dtype: float64

Comprobación de duplicados

In [ ]:
# duplicated() marca como True cualquier fila que sea idéntica a una anterior
print("Filas totalmente duplicadas en ventas:", ventas.duplicated().sum())
print("Filas totalmente duplicadas en clientes:", clientes.duplicated().sum())

# También conviene revisar duplicados por una clave de negocio específica,
# Por ejemplo: ¿algún CustomerID
# aparece más de una vez en la tabla de clientes? (no debería, es su clave única)
duplicados_customerid = clientes[clientes.duplicated(subset='CustomerID', keep=False)]
print("\nCustomerID duplicados en clientes:")
display(duplicados_customerid)

Filas totalmente duplicadas en ventas: 0
Filas totalmente duplicadas en clientes: 0

CustomerID duplicados en clientes:

Empty DataFrame
Columns: [CustomerID, Country, Segmento]
Index: []

Revisión de valores categóricos

In [ ]:
print("Países en ventas:", ventas['Country'].unique())
print("Países en clientes:", clientes['Country'].unique())
print("Categorías en ventas:", ventas['Categoria'].unique())
print("Segmentos en clientes:", clientes['Segmento'].unique())

Países en ventas: ['United Kingdom' 'France']
Países en clientes: ['United Kingdom' 'France' 'Germany']
Categorías en ventas: ['Decoracion' 'Regalos']
Segmentos en clientes: ['Minorista' 'Mayorista']

Preparar columna de ingresos

In [ ]:
# Antes de agrupar necesitamos una métrica numérica que agregar.
# IngresosBrutos = cantidad vendida x precio unitario, por cada línea de venta
ventas["IngresosBrutos"] = ventas["Quantity"] * ventas["UnitPrice"]

ventas[["InvoiceNo", "Description", "Country", "Categoria", "IngresosBrutos"]].head()

,InvoiceNo,Description,Country,Categoria,IngresosBrutos
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom,Decoracion,15.30
1,536365,WHITE METAL LANTERN,United Kingdom,Decoracion,20.34
2,536366,HAND WARMER UNION JACK,United Kingdom,Regalos,11.10
3,536367,ASSORTED COLOUR BIRD ORNAMENT,United Kingdom,Regalos,54.08
4,536367,FELTCRAFT PRINCESS CHARLOTTE DOLL,United Kingdom,Regalos,30.00

Dividir en grupos

In [ ]:
# groupby() por sí solo NO calcula nada todavía: solo organiza las filas en grupos.
grupos_por_pais = ventas.groupby("Country")

# Podemos inspeccionar cuántos grupos se formaron y cuáles son
print("Grupos formados:", list(grupos_por_pais.groups.keys()))

# Y podemos ver, por ejemplo, qué filas cayeron en el grupo "France"
grupos_por_pais.get_group("France")

Grupos formados: ['France', 'United Kingdom']

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Categoria,IngresosBrutos
6,536370,22728,ALARM CLOCK BAKELIKE PINK,24,3.75,12583,France,Regalos,90.0
7,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,2.95,12583,France,Decoracion,53.1
8,536370,22629,SPACEBOY LUNCH BOX,24,1.95,12583,France,Regalos,46.8
17,C536501,22728,ALARM CLOCK BAKELIKE PINK,-24,3.75,12583,France,Regalos,-90.0

Aplicar y combinar

In [ ]:
# Al encadenar una función de agregación, pandas aplica esa función a CADA grupo
# por separado (apply) y luego junta los resultados en una sola tabla (combine)
ingresos_por_pais = ventas.groupby("Country")["IngresosBrutos"].sum()

print(ingresos_por_pais)

Country
France              99.90
United Kingdom    1140.08
Name: IngresosBrutos, dtype: float64

Verificación

In [ ]:
# Esto es exactamente lo mismo que la celda anterior, pero hecho
# grupo por grupo, para que quede clarísimo que groupby no hace magia:
# solo automatiza este mismo proceso.
for pais, grupo in ventas.groupby("Country"):
    total = grupo["IngresosBrutos"].sum()
    print(f"{pais}: ${total:,.2f}  (a partir de {len(grupo)} filas)")

France: $99.90  (a partir de 4 filas)
United Kingdom: $1,140.08  (a partir de 14 filas)

Uso de apply

In [ ]:
# La fase "apply" puede ser cualquier función de agregación: sum, mean, count, max...
print("Promedio de ingreso por línea de venta, por país:")
print(ventas.groupby("Country")["IngresosBrutos"].mean())

print("\nNúmero de líneas de venta por país:")
print(ventas.groupby("Country")["IngresosBrutos"].count())

Promedio de ingreso por línea de venta, por país:
Country
France            24.975000
United Kingdom    81.434286
Name: IngresosBrutos, dtype: float64

Número de líneas de venta por país:
Country
France             4
United Kingdom    14
Name: IngresosBrutos, dtype: int64

Agrupar por más de una clave a la vez

In [ ]:
# También podemos "dividir" usando más de una columna, pasando una lista.
# Aquí agrupamos por País Y Categoría al mismo tiempo.
ingresos_pais_categoria = ventas.groupby(["Country", "Categoria"])["IngresosBrutos"].sum()

print(ingresos_pais_categoria)

Country         Categoria
France          Decoracion     53.10
                Regalos        46.80
United Kingdom  Decoracion    948.54
                Regalos       191.54
Name: IngresosBrutos, dtype: float64

Mantener las claves como columnas normales

In [ ]:
# Por defecto, las columnas de agrupación se convierten en índice del resultado.
# Con as_index=False, se mantienen como columnas normales, lo cual suele ser
# más cómodo para seguir trabajando con el resultado (por ejemplo, para graficarlo después)
resumen = ventas.groupby(["Country", "Categoria"], as_index=False)["IngresosBrutos"].sum()

resumen

          Country   Categoria  IngresosBrutos
0          France  Decoracion           53.10
1          France     Regalos           46.80
2  United Kingdom  Decoracion          948.54
3  United Kingdom     Regalos          191.54

Diferencia entre size y count

In [ ]:
# .size() cuenta el número de FILAS del grupo, sin importar si hay nulos
# .count() cuenta valores NO NULOS de una columna específica

print("size():", ventas.groupby("Country").size())
print("\ncount() sobre CustomerID:", ventas.groupby("Country")["CustomerID"].count())

size(): Country
France             4
United Kingdom    14
dtype: int64

count() sobre CustomerID: Country
France             4
United Kingdom    14
Name: CustomerID, dtype: int64

Múltiples métricas con groupby

In [ ]:
# Si quisiéramos varias métricas con groupby "simple", tendríamos que repetir
# la agrupación una y otra vez — ineficiente y poco legible
ingresos = ventas.groupby("Country")["IngresosBrutos"].sum()
unidades = ventas.groupby("Country")["Quantity"].sum()
num_facturas = ventas.groupby("Country")["InvoiceNo"].nunique()

print(ingresos)
print(unidades)
print(num_facturas)

Country
France              99.90
United Kingdom    1140.08
Name: IngresosBrutos, dtype: float64
Country
France             42
United Kingdom    322
Name: Quantity, dtype: int64
Country
France            2
United Kingdom    9
Name: InvoiceNo, dtype: int64

Múltiples métricas con .agg()

In [ ]:
# .agg() permite calcular varias métricas en una sola pasada por los datos.
# Sintaxis: nombre_columna_resultado=("columna_origen", "funcion")
resumen_pais = ventas.groupby("Country").agg(
    ingresos_totales=("IngresosBrutos", "sum"),
    unidades_vendidas=("Quantity", "sum"),
    num_facturas=("InvoiceNo", "nunique"),   # nunique = facturas DISTINTAS, no líneas
    num_lineas=("InvoiceNo", "count"),        # count = total de líneas de venta
)

resumen_pais

                ingresos_totales  unidades_vendidas  num_facturas  num_lineas
Country
France                     99.90                 42             2           4
United Kingdom           1140.08                322             9          14

nunique vs count

In [ ]:
# Una misma factura puede tener varias líneas (varios productos comprados juntos).
# nunique() cuenta facturas ÚNICAS; count() cuenta cada LÍNEA por separado.

uk = ventas[ventas["Country"] == "United Kingdom"]

print("Facturas distintas (nunique):", uk["InvoiceNo"].nunique())
print("Líneas de venta totales (count):", uk["InvoiceNo"].count())
print("\nEsto pasa porque varias líneas comparten el mismo InvoiceNo:")
print(uk["InvoiceNo"].value_counts())

Facturas distintas (nunique): 9
Líneas de venta totales (count): 14

Esto pasa porque varias líneas comparten el mismo InvoiceNo:
InvoiceNo
536365    2
536367    2
536378    2
536376    2
536373    2
536371    1
536368    1
536366    1
536374    1
Name: count, dtype: int64

Varias funciones en una misma columna

In [ ]:
# También se puede pedir varias funciones sobre una sola columna.
# Aquí usamos la sintaxis de lista en vez de tuplas nombradas.
estadisticas_ingresosBrutos = ventas.groupby("Country")["IngresosBrutos"].agg(["sum", "mean", "min", "max"])

estadisticas_ingresosBrutos

                    sum       mean    min    max
Country
France            99.90  24.975000 -90.00   90.0
United Kingdom  1140.08  81.434286   6.36  350.4

Agregaciones múltiples con doble clave de agrupación (Categoría por País)

In [ ]:

resumen_pais_categoria = ventas.groupby(["Country", "Categoria"], as_index=False).agg(
    ingresos_totales=("IngresosBrutos", "sum"),
    unidades_vendidas=("Quantity", "sum"),
    num_lineas=("InvoiceNo", "count"),
)
#País y categoría con mayores ventas
resumen_pais_categoria.sort_values("ingresos_totales", ascending=False)

          Country   Categoria  ingresos_totales  unidades_vendidas  num_lineas
2  United Kingdom  Decoracion            948.54                242           7
3  United Kingdom     Regalos            191.54                 80           7
0          France  Decoracion             53.10                 18           1
1          France     Regalos             46.80                 24           3

Tipos de merge

Tablas originales

In [ ]:
print("Tabla ventas:", ventas.shape)
print(ventas[["InvoiceNo", "CustomerID", "Country"]].drop_duplicates())

print("\nTabla clientes:", clientes.shape)
print(clientes)

Tabla ventas: (18, 9)
   InvoiceNo  CustomerID         Country
0     536365       17850  United Kingdom
2     536366       17850  United Kingdom
3     536367       13047  United Kingdom
5     536368       13047  United Kingdom
6     536370       12583          France
9     536371       13748  United Kingdom
10    536373       17850  United Kingdom
12    536374       15100  United Kingdom
13    536376       15291  United Kingdom
15    536378       14688  United Kingdom
17   C536501       12583          France

Tabla clientes: (8, 3)
   CustomerID         Country   Segmento
0       17850  United Kingdom  Minorista
1       13047  United Kingdom  Minorista
2       12583          France  Mayorista
3       13748  United Kingdom  Minorista
4       15100  United Kingdom  Mayorista
5       15291  United Kingdom  Minorista
6       14688  United Kingdom  Minorista
7       16000         Germany  Minorista

Primer merge: unión por customerID

In [ ]:
# Unimos por CustomerID. OJO: ambas tablas tienen una columna "Country",
# así que pandas va a renombrarlas automáticamente con sufijos _x / _y
primer_intento = ventas.merge(clientes, on="CustomerID", how="inner")

primer_intento[["InvoiceNo", "CustomerID", "Country_x", "Country_y", "Segmento"]].head()

  InvoiceNo  CustomerID       Country_x       Country_y   Segmento
0    536365       17850  United Kingdom  United Kingdom  Minorista
1    536365       17850  United Kingdom  United Kingdom  Minorista
2    536366       17850  United Kingdom  United Kingdom  Minorista
3    536367       13047  United Kingdom  United Kingdom  Minorista
4    536367       13047  United Kingdom  United Kingdom  Minorista

Corrección

In [ ]:
# Como Country ya existe en ventas y es la misma información, no necesitamos
# traerla de nuevo desde clientes. Seleccionamos solo lo que aporta valor nuevo.
clientes_merge = clientes[["CustomerID", "Segmento"]]

ventas_con_cliente = ventas.merge(clientes_merge, on="CustomerID", how="inner")

ventas_con_cliente.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Categoria,IngresosBrutos,Segmento
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,Decoracion,15.30,Minorista
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,Decoracion,20.34,Minorista
2,536366,22633,HAND WARMER UNION JACK,6,1.85,17850,United Kingdom,Regalos,11.10,Minorista
3,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,13047,United Kingdom,Regalos,54.08,Minorista
4,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,3.75,13047,United Kingdom,Regalos,30.00,Minorista

Inner Join

In [ ]:
inner = ventas.merge(clientes_merge, on="CustomerID", how="inner")

print("Filas resultantes (inner):", inner.shape[0])
print("Filas originales en ventas:", ventas.shape[0])
# Como TODOS los CustomerID de ventas existen en clientes, inner no pierde ninguna fila.
# El único que se queda fuera es el 16000, porque nunca aparece en ventas.

Filas resultantes (inner): 18
Filas originales en ventas: 18

left Join

In [ ]:
left = ventas.merge(clientes_merge, on="CustomerID", how="left")

print("Filas resultantes (left):", left.shape[0])
# Da lo mismo que inner en este caso, porque no hay ningún CustomerID en ventas
# que falte en clientes. Left solo se nota cuando el lado izquierdo tiene huérfanos.

Filas resultantes (left): 18

Right Join

In [ ]:
right = ventas.merge(clientes_merge, on="CustomerID", how="right")

print("Filas resultantes (right):", right.shape[0])
print("\nAquí SÍ aparece el cliente 16000, con NaN en las columnas de ventas:")
right[right["CustomerID"] == 16000]

Filas resultantes (right): 19

Aquí SÍ aparece el cliente 16000, con NaN en las columnas de ventas:

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Categoria,IngresosBrutos,Segmento
18,NaN,NaN,NaN,NaN,NaN,16000,NaN,NaN,NaN,Minorista

Outer Join

In [ ]:
outer = ventas.merge(clientes_merge, on="CustomerID", how="outer")

print("Filas resultantes (outer):", outer.shape[0])
# outer = inner + los huérfanos de la izquierda + los huérfanos de la derecha
# En este caso da igual que right, porque ventas no tiene huérfanos propios.

Filas resultantes (outer): 19

Comparacion entre los 4 tipos de merge

In [ ]:
comparacion = pd.DataFrame({
    "tipo_union": ["inner", "left", "right", "outer"],
    "filas_resultantes": [inner.shape[0], left.shape[0], right.shape[0], outer.shape[0]],
})

comparacion

  tipo_union  filas_resultantes
0      inner                 18
1       left                 18
2      right                 19
3      outer                 19

Verificar filas sin coincidencias despues del merge

In [ ]:
# Sin importar qué tipo de unión uses, SIEMPRE conviene revisar cuántas filas
# quedaron con NaN en las columnas que vinieron de la tabla derecha.
# Esto detecta problemas de unión antes de generar un reporte.
nulos_tras_merge = right["Segmento"].isna().sum()
print(f"Filas sin Segmento asignado tras el right join: {nulos_tras_merge}")

right[right["Segmento"].isna()]

Filas sin Segmento asignado tras el right join: 0

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID, Country, Categoria, IngresosBrutos, Segmento]
Index: []

Pivot Table

In [ ]:
# Esto ya lo hicimos con groupby: País x Categoría, en formato "largo"
resumen_largo = ventas.groupby(["Country", "Categoria"])["IngresosBrutos"].sum()
print(resumen_largo)

Country         Categoria
France          Decoracion     53.10
                Regalos        46.80
United Kingdom  Decoracion    948.54
                Regalos       191.54
Name: IngresosBrutos, dtype: float64

In [ ]:
tabla_pais_categoria = pd.pivot_table(
    ventas,
    index="Country",       # esto va en las FILAS
    columns="Categoria",   # esto va en las COLUMNAS
    values="IngresosBrutos",      # esto es lo que se agrega
    aggfunc="sum",         # cómo se agrega (igual que en groupby)
)

tabla_pais_categoria

Categoria       Decoracion  Regalos
Country
France               53.10    46.80
United Kingdom      948.54   191.54

manejar espacios blancos de información

In [ ]:
# Si algún país no tiene ventas en alguna categoría, esa celda queda en NaN.
# fill_value reemplaza esos huecos por un valor explícito (normalmente 0)
tabla_pais_categoria = pd.pivot_table(
    ventas,
    index="Country",
    columns="Categoria",
    values="IngresosBrutos",
    aggfunc="sum",
    fill_value=0,   # sin esto, Francia mostraría NaN si no tuviera alguna categoría
)

tabla_pais_categoria

Categoria       Decoracion  Regalos
Country
France               53.10    46.80
United Kingdom      948.54   191.54

Agregar totales de fila y columna

In [ ]:
# margins=True agrega una fila y una columna de "Total", muy típico en reportes ejecutivos
tabla_con_totales = pd.pivot_table(
    ventas,
    index="Country",
    columns="Categoria",
    values="IngresosBrutos",
    aggfunc="sum",
    fill_value=0,
    margins=True,          # agrega fila/columna "All"
    margins_name="Total",  # le cambiamos el nombre a "Total" en vez de "All"
)

tabla_con_totales

Categoria       Decoracion  Regalos    Total
Country
France               53.10    46.80    99.90
United Kingdom      948.54   191.54  1140.08
Total              1001.64   238.34  1239.98

Múltiples métricas

In [ ]:
# aggfunc también puede recibir una lista, igual que en agg()
tabla_multi_metrica = pd.pivot_table(
    ventas,
    index="Country",
    columns="Categoria",
    values="IngresosBrutos",
    aggfunc=["sum", "mean", "count"],
    fill_value=0,
)

tabla_multi_metrica

                      sum                mean                 count
Categoria      Decoracion Regalos  Decoracion    Regalos Decoracion Regalos
Country
France              53.10   46.80   53.100000  15.600000          1       3
United Kingdom     948.54  191.54  135.505714  27.362857          7       7

Invirtiendo filas y columnas

In [ ]:
# Categoría en filas, País en columnas: mismo resultado, otra orientación.
# Útil para decidir cuál se lee mejor según cuántas categorías/países tengas.
tabla_invertida = pd.pivot_table(
    ventas,
    index="Categoria",
    columns="Country",
    values="IngresosBrutos",
    aggfunc="sum",
    fill_value=0,
)

tabla_invertida

Country     France  United Kingdom
Categoria
Decoracion    53.1          948.54
Regalos       46.8          191.54

groupby + reshape

In [ ]:
paso1 = ventas.groupby(["Country", "Categoria"])["IngresosBrutos"].sum()

# ..unstack() convierte
# el segundo nivel del índice en columnas, que es justo lo que hace pivot_table.
paso2 = paso1.unstack(fill_value=0)

print(paso2)
print("\nSon iguales?", paso2.equals(tabla_pais_categoria))

Categoria       Decoracion  Regalos
Country
France               53.10    46.80
United Kingdom      948.54   191.54

Son iguales? True

KPI

KPI #1: Ticket promedio

In [ ]:
# El "ticket" es el total de una factura completa, no de una sola línea de venta.
# Por eso primero agrupamos por Ingreso antes de calcular el promedio.
ingresos_por_factura = ventas.groupby("InvoiceNo")["IngresosBrutos"].sum()

print(ingresos_por_factura)

ticket_promedio = ingresos_por_factura.mean()
print(f"\nTicket promedio: ${ticket_promedio:,.2f}")

InvoiceNo
536365      35.64
536366      11.10
536367      84.08
536368      25.50
536370     189.90
536371     204.00
536373      36.06
536374     350.40
536376     328.80
536378      64.50
C536501    -90.00
Name: IngresosBrutos, dtype: float64

Ticket promedio: $112.73

Ticket promedio (bruto vs neto)

In [ ]:
ticket_promedio_bruto = ingresos_por_factura.mean()

# Para la versión "neta", excluimos las facturas canceladas (las que empiezan con "C")
ventas_sin_cancelaciones = ventas[~ventas["InvoiceNo"].astype(str).str.startswith("C")]
ingresos_por_factura_neto = ventas_sin_cancelaciones.groupby("InvoiceNo")["IngresosBrutos"].sum()
ticket_promedio_neto = ingresos_por_factura_neto.mean()

print(f"Ticket promedio (bruto, con cancelaciones): ${ticket_promedio_bruto:,.2f}")
print(f"Ticket promedio (neto, sin cancelaciones):  ${ticket_promedio_neto:,.2f}")

Ticket promedio (bruto, con cancelaciones): $112.73
Ticket promedio (neto, sin cancelaciones):  $133.00

KPI #2: Top n productos por ingresos

In [ ]:

top_productos = (
    ventas_sin_cancelaciones
    .groupby("Description")["IngresosBrutos"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_productos

Description
VICTORIAN SEWING BOX LARGE           350.4
PAPER CHAIN KIT 50'S CHRISTMAS       204.0
HOT WATER BOTTLE TEA AND SYMPATHY    165.6
RED HANGING HEART T-LIGHT HOLDER     163.2
ALARM CLOCK BAKELIKE PINK             90.0
Name: IngresosBrutos, dtype: float64

Top-N clientes por ingresos

In [ ]:
# El mismo patrón, pero agrupando por cliente en lugar de por producto
top_clientes = (
    ventas_sin_cancelaciones
    .groupby("CustomerID")["IngresosBrutos"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_clientes

CustomerID
15100    350.40
15291    328.80
13748    204.00
12583    189.90
13047    109.58
Name: IngresosBrutos, dtype: float64

KPI #3: Tasa de cancelación

In [ ]:
# Marcamos qué facturas son cancelaciones (prefijo "C" en InvoiceNo)
ventas["EsCancelacion"] = ventas["InvoiceNo"].astype(str).str.startswith("C")

# La tasa de cancelación se calcula sobre FACTURAS distintas, no sobre líneas de venta
facturas_totales = ventas["InvoiceNo"].nunique()
facturas_canceladas = ventas.loc[ventas["EsCancelacion"], "InvoiceNo"].nunique()

tasa_cancelacion = facturas_canceladas / facturas_totales

print(f"Facturas totales: {facturas_totales}")
print(f"Facturas canceladas: {facturas_canceladas}")
print(f"Tasa de cancelación: {tasa_cancelacion:.1%}")

Facturas totales: 11
Facturas canceladas: 1
Tasa de cancelación: 9.1%

Tasa de cancelación por país

In [ ]:
cancelacion_por_pais = (
    ventas.groupby("Country")
    .agg(
        facturas_totales=("InvoiceNo", "nunique"),
        facturas_canceladas=("EsCancelacion", "sum"),  # sum de booleanos = conteo de True
    )
)

cancelacion_por_pais["tasa_cancelacion"] = (
    cancelacion_por_pais["facturas_canceladas"] / cancelacion_por_pais["facturas_totales"]
)

cancelacion_por_pais

                facturas_totales  facturas_canceladas  tasa_cancelacion
Country
France                         2                    1               0.5
United Kingdom                 9                    0               0.0

KPI #4: Frecuencia de compra por cliente

In [ ]:
# ¿Cuántas facturas distintas generó cada cliente?
frecuencia_por_cliente = (
    ventas_sin_cancelaciones
    .groupby("CustomerID")["InvoiceNo"]
    .nunique()
    .sort_values(ascending=False)
)

frecuencia_por_cliente

CustomerID
17850    3
13047    2
12583    1
13748    1
14688    1
15100    1
15291    1
Name: InvoiceNo, dtype: int64

Resumen ejecutivo

In [ ]:
print("=== Resumen ejecutivo ===")
print(f"Ticket promedio (neto): ${ticket_promedio_neto:,.2f}")
print(f"Producto más vendido: {top_productos.index[0]} (${top_productos.iloc[0]:,.2f})")
print(f"Tasa de cancelación global: {tasa_cancelacion:.1%}")
print(f"Cliente más frecuente: {frecuencia_por_cliente.index[0]} ({frecuencia_por_cliente.iloc[0]} facturas)")

=== Resumen ejecutivo ===
Ticket promedio (neto): $133.00
Producto más vendido: VICTORIAN SEWING BOX LARGE ($350.40)
Tasa de cancelación global: 9.1%
Cliente más frecuente: 17850 (3 facturas)